### ISSUE TITLE
error: For non git repositories explicit revisions are required

### ISSUE THREAD

**Issue by pqr** [getsentry/sentry-cli#115]
I use sentry.io and sentry-cli 1.19.1

Trying to setup releases as described in docs docs: https://docs.sentry.io/learn/cli/releases/
My script:
```
export SENTRY_AUTH_TOKEN=<token>
export SENTRY_ORG=<myorg>
VERSION=$(sentry-cli releases propose-version)
sentry-cli releases new -p <myproj> $VERSION
sentry-cli releases set-commits --auto $VERSION
```
Release appears on sentry.io UI as expected.
But last command (set-commits) always shows following message: "`error: For non git repositories explicit revisions are required`" and when I look into "commits" tab within sentry.io UI - there are no commits :(
My current directory 100% is under git.
I tried this script from my macbook macOS 10.12.6 and from server Ubuntu 16.04 - both show "`error: For non git repositories explicit revisions are required`".

Then I tried different approach:
`sentry-cli releases set-commits $VERSION --commit "<repo name>@<last commit sha inserted manually>"` - this works and now I see commits in "commits" tab within sentry.io UI.

What's wrong with `sentry-cli releases set-commits --auto $VERSION`? How to debug?

**Comment by pqr** [comment]
Looking into source code: https://github.com/getsentry/sentry-cli/blob/185bb432f55b22dd9bcda0c5bf205c2399511138/src/utils/vcs.rs#L131

provider.id must be "github" or "git"

In my case I have a private git repository on Bitbucket, and command `sentry-cli repos list` shows me:
```
+---------+-----------+-------------------------------+
| Name    | Provider  | URL                           |
+---------+-----------+-------------------------------+
| <myrep> | Bitbucket | https://bitbucket.org/<myrep> |
+---------+-----------+-------------------------------+
```

So no chance for the moment to use `--auto` and Bitbucket hosted private git repository?
Actually all the repository history is available locally in `.git` folder (from where I run the script), why `sentry-cli` can't use local repository to search for commits?

**Comment by mitsuhiko** [comment]
This will be fixed in the next release of sentry-cli.

**Comment by dcramer** [comment]
The problem is you won't be able to register the repository in sentry currently without it being added from one of the available providers.

**Comment by mitsuhiko** [comment]
I fixed the missing URL parsing here: https://github.com/getsentry/sentry-cli/commit/f1020de352c112d5a06c1e96c9d52bd68c31d244 - supports bitbucket now.

**Comment by G-Rath** [comment]
When can we expect this to be released? We're starting to make use of the sentry-cli for releases, and only have BitBucket repos, so it would be great to have :)

**Comment by mitsuhiko** [comment]
I will push out a release tomorrow I think.

**Comment by Amnacog** [comment]
installed the freshly 1.20, and still have the message with this in `.git/config`

```
[remote "origin"]
	url = ssh://git@bitbucket.org/...
```

**Comment by G-Rath** [comment]
@mitsuhiko I can confirm that this is still happening.

I've updated to 1.20, and get `error: For non git repositories explicit revisions are required`.

I've looked at the json returned, and can confirm that all repos on Sentry are `https://bitbucket.org/...`, and that in my git config the url is `ssh://git@bitbucket.org/...`

**Comment by G-Rath** [comment]
@mitsuhiko

https://github.com/getsentry/sentry-cli/commit/f1020de352c112d5a06c1e96c9d52bd68c31d244#diff-4faa75712a7ea67c61fe23e83663079dR140

Methinks that line could be the issue ;)

**Comment by mitsuhiko** [comment]
Indeed.

**Comment by G-Rath** [comment]
Any chance of getting a fix released anytime soon?

It's a pretty big bug given it breaks all support for bitbucket as a provider.

I'd make a PR personally, but I don't have Rust installed (nor have I used it before).
