### ISSUE TITLE
Can not install on Ubuntu workspaces Linux 5.15.0-1026-aws

### ISSUE THREAD

**Issue by harmoney-anle** [getsentry/sentry-cli#1478]
Hi guys,

I am trying to install and using `"@sentry/nextjs": "^7.31.1`" in my local system that is a Ubuntu Workspaces on AWS.

I run  install command like this `npm i --legacy-peer-deps`

then got this error
````
npm ERR! code 1
npm ERR! path /home/node_modules/@sentry/cli
npm ERR! command failed
npm ERR! command sh -c node ./scripts/install.js

npm ERR! A complete log of this run can be found in:`
```



Here is the log inside debug log file: 
```
488 timing command:i Completed in 22703ms
489 verbose stack Error: command failed
489 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
489 verbose stack     at ChildProcess.emit (node:events:513:28)
489 verbose stack     at maybeClose (node:internal/child_process:1091:16)
489 verbose stack     at Socket.<anonymous> (node:internal/child_process:449:11)
489 verbose stack     at Socket.emit (node:events:513:28)
489 verbose stack     at Pipe.<anonymous> (node:net:320:12)
490 verbose pkgid @sentry/cli@1.74.6
492 verbose Linux 5.15.0-1026-aws
493 verbose node v18.13.0
494 verbose npm  v9.5.0
495 error code 1
496 error path //node_modules/@sentry/cli
497 error command failed
498 error command sh -c node ./scripts/install.js
499 verbose exit 1
```

I researched this for a day and still can not fix it.
Could anyone have same issue or any idea for workaround on this?

**Comment by kamilogorek** [comment]
Should be fixed now. Sorry for inconvenience.

**Comment by harmoney-anle** [comment]
I have just tried again, it does not work. Any suggestion for the fix?

**Comment by kamilogorek** [comment]
Can you try `cd node_modules/@sentry/cli` and then run `node scripts/install.js` directly? Maybe it'll show more detailed logs this way.

**Comment by harmoney-anle** [comment]
Hi @kamilogorek, I have run the install.js as your suggestion. It downloaded a file named fd2dc7-sentry-cli-Linux-x86-64 and put it inside .npm/sentry-cli, and then I try npm i --legacy-peer-deps once again. It still the same error.
Could you have any suggestions on this?

**Comment by kamilogorek** [comment]
Unfortunately without an actual repro-case, it's impossible to tell what went wrong here.
Our installation script has logging in place, but it appears that `sh -c node` itself is failing here, not the installation script.

You can try to install the cli binary manually by doing `npm -i --ignore-scripts` and then

```
curl https://github.com/getsentry/sentry-cli/releases/download/2.13.0/sentry-cli-Linux-x86_64 > /home/node_modules/@sentry/cli/sentry-cli
```

It might need additional `chmod` change to make it executable though, not sure about AWS settings there.

**Comment by harmoney-anle** [comment]
Thanks for your help, it looks works in my local.
