### ISSUE TITLE
Broken source file after uploading sourcemaps

### ISSUE THREAD

**Issue by danielpoonwj** [getsentry/sentry-cli#1532]
### Environment

`v2.15.1`

### Steps to Reproduce

Uploading sourcemaps produces a broken source file.

![Screenshot 2023-03-17 at 7 43 58 PM](https://user-images.githubusercontent.com/17039704/225898200-8b108698-a55d-4e7d-af9a-050b6920e5aa.png)

This is a very severe error as it prevented the page from loading. Rolling back to `v2.14.4` fixed the issue, I suspect that some source code modifications when adding debug ids caused this.

**Comment by ashwoods** [comment]
@danielpoonwj Hey! Thanks for the bug report; we are looking into this right now.

**Comment by Swatinem** [comment]
> I suspect that some source code modifications when adding debug ids caused this.

We are indeed now injecting a small snippet of JS to all the source files. Though that snippet should be safe to append to any valid JS file, which according to your error message clearly is not the case for your file.

Can you attach the last couple of lines of the file that is causing this error? That should include (from the end): the `debugId` comment, the `sourceMappingURL`, and the injected snippet of JS, and then your own minified code.

Or even a diff of your file before/after you are calling `sentry-cli`? It might be possible that the injection is broken in some way that were not able to reproduce with our own source files.

**Comment by NSiggel** [comment]
!! Just to confirm this is indeed a bug we are seeing as part of our automated deployments !!

![image](https://user-images.githubusercontent.com/11523121/225954831-40724293-cf76-4727-a3f0-b2ac88dfc67e.png)
![image](https://user-images.githubusercontent.com/11523121/225954990-da37b881-917d-400a-96d8-a4d0e8681719.png)

Currently adding explicit Sentry CLI version to our Buildspec file,  which has fixed the issue for now, 
- curl -sL https://sentry.io/get-cli/ | SENTRY_CLI_VERSION=2.14.4 bash

**Comment by ashwoods** [comment]
We released a hotfix reverting the default.

**Comment by ianformanek** [comment]
Just to be sure you are aware: in our case our app was rendered unusable because of the source modification after fingerprinting / integrity hashing. It does not seem correct to assume that injecting additional code as part of source map upload would be without possible side-effects.

**Comment by loewenheim** [comment]
Thank you for the report, that is indeed something we will have to reconsider.

**Comment by hellvinz** [comment]
Same thing here, this change is breaking SRI. Modifying the files after they are generated from a build pipeline, this can't be a minor release

**Comment by ianformanek** [comment]
For apps with build pipelines that create fingerprinted assets, this can be particularly nasty, since the integrity-check breaking files stick in the CDN/browser caches. Even when you rebuild with the fix that no longer adds the `debug_id` (pinning to older version of the sentry-cli - 2.14.4 - or using the latest where it was made non-default), your users would still experience problems (possibly with a random subset of the assets) as the fingerprint has not changed.

There is no good way to reliably recover other than making sure every single asset where the `debug_id` was added is changed to end up with a different fingerprint. Alternatively, CDN (CloudFront in our case) invalidation should help with most issues, together with asking the users to do a hard refresh of the browser tab.

**Comment by TheSlimvReal** [comment]
Damn, this is a very serious bug that caused a lot of problems for me. I am using service workers and modifying source files **after** the build step is a big **NO NO** because the hashes for the files will differ and therefore the service workers will be in an error state when receiving these modified source files. This should definitely be noted for the new, now optional option and also be reminded for future features. It took me quite some time to find where this issue is coming from (my issue for using `sentry-cli@latest` in my build pipeline).

**Comment by eXaminator** [comment]
In our case this update broke our pipeline with the following error:

```
> Rewriting sources
error: bad json: trailing characters at line 1 column 9226
```

Another thought: We build a docker image with our app in it and then just upload the generated source maps AFTER the fact. While I'm not sure what the injected debug IDs are used for, the code with the debug IDs would never end up in our docker image and would never run on the client in our case and the sourcemaps might not match the actual code anymore.

**Comment by Swatinem** [comment]
That is valuable feedback, thanks!

`DebugId`s are a way to uniquely identify the minified file / sourcemap to use those for sourcemap processing.
We have found that the current way of using release + dist is not very reliable, and has caused lots of problems.
`DebugId`s should help with those.

The challenge then becomes how to embed those into the JS files, so they are available at runtime to attach to events.

**Comment by mitsuhiko** [comment]
I think all of this is a strong argument for making the `inject` step explicit, particularly from the doc perspective. That way it's more obvious that you need to inject within the docker image even if the upload takes place later.

**Comment by ashwoods** [comment]
@NSiggel Could you provide us more information about your bundler configuration and how you are using `sentry-cli`? Feel free to email me or ping me on discord if you want this to be private.

**Comment by Swatinem** [comment]
Hi everyone! Another update from our team.

We went through this incident recently to figure out what happened, and this is our conclusion:

We have feature-flags in place for this whole feature, both in our backend code, and in other places of `sentry-cli`. The companion `sentry-cli inject` command is completely hidden for example. When integrating that code path into the `sentry-cli upload` command, it should have been feature-flagged as well.
The injection was not meant to be turned on by default. This was a major oversight that slipped past us, and we are sorry this has caused such pain for our users.

We were pushing for a working prototype to test and dogfood, to validate that our ideas are actually working as intended. In this phase of the development, we did not consider every use case. For example, SRI was not on our radar so far.

Some of the confusion might also come from the fact that this has been an almost "secret" initiative, with only some internal documentation around it. We should have involved our customers and the broader JS tools community earlier in the planning.

To remedy this situation, we have prepared a public (Sentry) RFC to solicit feedback and discussion: https://github.com/getsentry/rfcs/pull/81
This document explains what problems we like to solve, and why we need to modify files prior to deployment, and what the snippet does that we inject.

We would love to hear your feedback on this proposal, and would like to learn more about how you deploy your JS code. Based on the feedback in this thread, I have expanded the proposal with a discussion around what SRI is and how it factors into all of this.
I’m sure I have not anticipated all the edge-cases, and there sure are more gaps to fill. Please provide your feedback and help us understanding this better.

**Comment by loewenheim** [comment]
Issues with incorrect injection should be resolved.
