### ISSUE TITLE
Quite confusing log message

### ISSUE THREAD

**Issue by lforst** [getsentry/sentry-cli#2137]
> WARN    2024-09-02 14:41:35.566111677 +00:00 Using https://sentry.io (embedded in token) rather than manually-configured URL https://sentry.io. To use https://sentry.io, please provide an auth token for this URL.

I am getting this in our Changelog Vercel logs. https://vercel.com/sentry/changelog/DT2tEb1huCLLTUm7DzDaWawhZHzi#L159

IMO, if the manually provided URL, and the URL in the auth token are matching, we should not print this message.

cc @szokeasaurusrex

**Comment by szokeasaurusrex** [comment]
strange – I thought I was only printing this when the two URLs are different, but I will double check

**Comment by szokeasaurusrex** [comment]
Okay, looks like in one of the places we emit this message we check whether the URLs are different, but in the other spot, we don't:

https://github.com/getsentry/sentry-cli/blob/288382f2b68f29cbee0c0b1a943b31bfbf4d0390/src/config.rs#L74-L83

Should be a pretty simple fix to add this check, thanks for raising @lforst!

**Comment by gregcotten** [comment]
I got a similar warning (note the forward slash at the end of one of the URLs)

`WARN    2024-09-04 14:32:54.675621700 -07:00 Using https://sentry.io/ (embedded in token) rather than manually-configured URL [https://sentry.io/.](https://sentry.io/) To use https://sentry.io/, please provide an auth token for this URL.`

**Comment by dmadridy** [comment]
Hey, just got this message as well when configuring Sentry. Let me know when its solved. Thanks!

**Comment by szokeasaurusrex** [comment]
@dmadridy hopefully we will get a fix out this week!

**Comment by szokeasaurusrex** [comment]
@dmadridy @lforst, the fix has been released in Sentry CLI v2.35.0.

**Comment by absolutegravitas** [comment]
yeesh... What is the actual patch and what does this mean? I have a repo https://github.com/midday-ai/v1 whose deployment to vercel fails because of this unnecessarily confusing message . Upgrading packages for that repo doesnt fix the issue (it's got `@sentry/nextjs` package).

- do i remove https prefix?
- do i provide auth token again?
- do i remove the https suffix towards the end?

yeesh

![Image](https://github.com/user-attachments/assets/38239b8b-7a4f-450c-b765-f3fa498936af)

**Comment by lforst** [comment]
@absolutegravitas The log message is confusing but it should not fail your build. You can basically ignore it.

**Comment by vonox7** [comment]
@szokeasaurusrex I'm using sentry-cli 2.39.1, however I still get the warning when calling `sentry-cli --url https://example.org/ sourcemaps upload --org example --project example-project ./dist/example-project`:

>   WARN    2024-12-12 12:57:54.724962 +01:00 Using https://example.org (embedded in token) rather than manually-configured URL https://example.org/. To use https://example.org/, please provide an auth token for this URL.

Note the missing trailing slash in the first url (embedded in token): I created the token via https://example.org/settings/arivo/auth-tokens/new-token/. However, when adding the sentry-cli to my Angular project with `npx @sentry/wizard@latest -i sourcemaps` (version 3.36.0) the wizard added the following line to the `package.json`, which contains the trailing slash on the url:

`    "sentry:sourcemaps": "sentry-cli sourcemaps inject --org example --project example-project ./dist/example-project && sentry-cli --url https://example.org/ sourcemaps upload --org example --project og-frontend-cx ./dist/example-project"`.

**So the workaround is to remove in `package.json` the trailing slash from the url:
`https://example.org/` --> `https://example.org`.**

**Comment by szokeasaurusrex** [comment]
@vonox7 this seems to be a bug/unintended behavior in the Sentry Wizard. If you are providing an auth token which embeds a URL, the Sentry Wizard should preferably avoid specifying any URL in the `package.json`, since Sentry CLI always will just use the URL embedded in the token
