### ISSUE TITLE
Symbol not found: _$s8RawValueSYTl with sentry-cli 2.50.1

### ISSUE THREAD

**Issue by IainS1986** [getsentry/sentry-cli#2642]
### CLI Version

2.250.1

### Operating System and Architecture

- [x] macOS (arm64)
- [ ] macOS (x86_64)
- [ ] Linux (i686)
- [ ] Linux (x86_64)
- [ ] Linux (armv7)
- [ ] Linux (aarch64)
- [ ] Windows (i686)
- [ ] Windows (x86_64)

### Operating System Version

macos-13 Azure Pipelines

### CLI Command

sentry-cli login --auth-token $(sentry.auth.token)

### Exact Reproduction Steps

Appears to have just happened with a new build and seems to have occured with 2.50.1 that *just* came out. 

Our brew install step shows 2.50.1 being installed.

`🍺  /usr/local/Cellar/sentry-cli/2.50.1: 4 files, 24.0MB, built in 3 seconds`

Might well be AzurePipeline issue with their mac build agent, but not sure.

This is the full output of our cli command call,

```
/bin/bash --noprofile --norc /Users/runner/work/_temp/f5853b34-4906-4887-a8e7-a2b601d83b04.sh
dyld[6158]: Symbol not found: _$s8RawValueSYTl
  Referenced from: <633FE77A-3FFB-31AA-9349-F259F83B47F7> /usr/local/Cellar/sentry-cli/2.50.1/bin/sentry-cli
  Expected in:     <no uuid> unknown
/Users/runner/work/_temp/f5853b34-4906-4887-a8e7-a2b601d83b04.sh: line 1:  6158 Abort trap: 6           sentry-cli login --auth-token ***

##[error]Bash exited with code '134'.
```

### Expected Results

Login command to execute as before.

### Actual Results

Error: dyld[6158]: Symbol not found: _$s8RawValueSYTl

### Logs

```
dyld[6158]: Symbol not found: _$s8RawValueSYTl
  Referenced from: <633FE77A-3FFB-31AA-9349-F259F83B47F7> /usr/local/Cellar/sentry-cli/2.50.1/bin/sentry-cli
  Expected in:     <no uuid> unknown
/Users/runner/work/_temp/f5853b34-4906-4887-a8e7-a2b601d83b04.sh: line 1:  6158 Abort trap: 6           sentry-cli login --auth-token ***
```

**Comment by IainS1986** [comment]
Realise now this step is still running on macos-13 agent, so switching to macos-latest (14) just to see if its an agent issue

**Comment by szokeasaurusrex** [comment]
Hi @IainS1986 – we will release a patch soon which should fix this.

**Comment by IainS1986** [comment]
Awesome 👍 thanks for the quick review!

**Comment by szokeasaurusrex** [comment]
Hopefully, the fix will be out in `2.50.2` within the next few minutes

**Comment by IainS1986** [comment]
Not sure if it makes any difference, but just FYI when I ran on macos-14 Azure pipeline images, I got an error still, but this time it stated `Library not loaded: @rpath/libswiftCore.dylib` instead

```
/bin/bash --noprofile --norc /Users/runner/work/_temp/4f61451c-9c79-4d9c-8bd7-ce641a9e2e6e.sh
dyld[3829]: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: <633FE77A-3FFB-31AA-9349-F259F83B47F7> /usr/local/Cellar/sentry-cli/2.50.1/bin/sentry-cli
  Reason: no LC_RPATH's found
/Users/runner/work/_temp/4f61451c-9c79-4d9c-8bd7-ce641a9e2e6e.sh: line 1:  3829 Abort trap: 6           sentry-cli login --auth-token ***

##[error]Bash exited with code '134'.
Finishing: Login to Sentry CLI
```

**Comment by IainS1986** [comment]
All sorted, can confirm 2.50.2 worked fine as before 👍
