### ISSUE TITLE
error: For non git repositories explicit revisions are required

### ISSUE THREAD

**Issue by tjg37** [getsentry/sentry-cli#371]
Trying to setup releases as described in docs docs: https://docs.sentry.io/learn/releases/

Following the steps: 

```
# Assumes you're in a git repository
export SENTRY_AUTH_TOKEN=...
export SENTRY_ORG=my-org
VERSION=$(sentry-cli releases propose-version)

# Create a release
sentry-cli releases new -p project1 -p project2 $VERSION

# Associate commits with the release
sentry-cli releases set-commits --auto $VERSION
```

All works well except for the last command `sentry-cli releases set-commits --auto $VERSION` which returns:
`error: For non git repositories explicit revisions are required`

```
sentry-cli --version
sentry-cli 1.35.4
```

This issue seems to be similar to https://github.com/getsentry/sentry-cli/issues/115 and https://github.com/getsentry/sentry-cli/issues/300, but unlike both of those issues, my repo is a Github repo: 

```
sentry-cli repos list
+----------------------------------+----------+-----------------------------------------------------+
| Name                             | Provider | URL                                                 |
+----------------------------------+----------+-----------------------------------------------------+
| getslideapp/slide-django-adaptor | GitHub   | https://github.com/getslideapp/slide-django-adaptor |
+----------------------------------+----------+-----------------------------------------------------+
```
One additional piece of information is that since I have multiple Github accounts on my machine, I use a configuration as described in this gist: https://gist.github.com/jexchan/2351996. As such, my github hostname is `github.com-tjg37` instead of `github.com`. I'm not sure if this is the source of the issue, but if it is, would it be possible to allow for hostnames of this form? 

```
git config --get remote.origin.url
git@github.com-tjg37:getslideapp/slide-django-adaptor.git
```

Also, as suggested in https://github.com/getsentry/sentry-cli/issues/115 and https://github.com/getsentry/sentry-cli/issues/300, if I manually add the previous commits `sentry-cli releases set-commits $VERSION --commit "$REPO@$VERSION"` it works.

**Comment by Zabanya** [comment]
same problem,  i'm using Bitbucket Pipelines and V2 connector
```
        - step:
            name: Sentry Release
            image: getsentry/sentry-cli
            script:
              - sentry-cli releases -o abc -p xyz new "$BITBUCKET_COMMIT"
              - sentry-cli releases -o abc -p xyz set-commits --auto "$BITBUCKET_COMMIT"
```

```
+-------------------------------+--------------+-----------------------------------------------------+
| Name                          | Provider     | URL                                                 |
+-------------------------------+--------------+-----------------------------------------------------+
| abc/xyz | Bitbucket v2 | https://bitbucket.org/abc/xyz |
+-------------------------------+--------------+-----------------------------------------------------+
```

**Comment by nijel** [comment]
Strarted to happen today to me as well. I've tried to upgrade sentry-cli to latest 1.35.5, but that made no difference.

Without knowing rust, I think the problem is here:

https://github.com/getsentry/sentry-cli/blob/7b119dfbd097a538d18fc6ebc6f41fd6917343e2/src/utils/vcs.rs#L172

As sentry since https://github.com/getsentry/sentry/commit/efcac0a82c364ffe1df09453efaada9910eab0c8#diff-0a897e12089601a38ba4d1841135961d uses `integrations:` prefix in the provider id while listing the repositories:

```json
[
    {
        "dateCreated": "2018-08-26T07:26:22.579Z",
        "id": "13618",
        "integrationId": "5604",
        "name": "WeblateOrg/weblate",
        "provider": {
            "id": "integrations:github",
            "name": "GitHub"
        },
        "status": "active",
        "url": "https://github.com/WeblateOrg/weblate"
    }
]
```

**Comment by jan-auer** [comment]
A fix has been released in version `1.35.6`. Thank you all for your patience and sharing this information!

**Comment by tjg37** [comment]
@jan-auer Thanks for pushing such a quick fix! 

However, the issue is not yet resolved for me. I am now getting a different error when running the command `sentry-cli releases set-commits --auto $VERSION`: 

`error: Could not determine any commits to be associated automatically. You will have to explicitly provide commits on the command line.`

Is this the expected behaviour in my case?

```
sentry-cli --version
sentry-cli 1.35.6
```

**Comment by Zabanya** [comment]
Bitbucket Pipelines and image getsentry/sentry-cli give me an OK

The Command
```
- step:
  name: Sentry Release
  image: getsentry/sentry-cli
  script:
    - sentry-cli -V
    - sentry-cli releases -o "$SENTRY_ORG" -p "$SENTRY_PROJECT" new "$BITBUCKET_COMMIT"
    - sentry-cli releases -o "$SENTRY_ORG" -p "$SENTRY_PROJECT" set-commits "$BITBUCKET_COMMIT" --auto
```

Result
```
+ umask 000

+ GIT_LFS_SKIP_SMUDGE=1 git clone --branch="master" --depth 50 https://x-token-auth:$REPOSITORY_OAUTH_ACCESS_TOKEN@bitbucket.org/hidden-org/hidden-proj.git $BUILD_DIR ; git reset --hard 6c5c5d67a400cee8f73eafa1f17dd3bc77bf23a0 ; git remote set-url origin git@bitbucket.org:hidden-org/hidden-proj.git
Cloning into '/opt/atlassian/pipelines/agent/build'...
HEAD is now at 6c5c5d6 move snyk to testing parallel

+ chmod 777 $BUILD_DIR

+ sentry-cli -V
sentry-cli 1.35.6

+ sentry-cli releases -o "$SENTRY_ORG" -p "$SENTRY_PROJECT" new "$BITBUCKET_COMMIT"
Created release 6c5c5d67a400cee8f73eafa1f17dd3bc77bf23a0.

+ sentry-cli releases -o "$SENTRY_ORG" -p "$SENTRY_PROJECT" set-commits "$BITBUCKET_COMMIT" --auto
+-------------------------------+--------------+
| Repository                    | Revision     |
+-------------------------------+--------------+
| hidden-org/hidden-proj | 6c5c5d67a400 |
+-------------------------------+--------------+
Searching for test report files in directories named [test-results, failsafe-reports, test-reports, surefire-reports] down to a depth of 4
Finished scanning for test reports. Found 0 test report files.
Merged test suites, total number tests is 0, with 0 failures and 0 errors.
```

**Comment by mitsuhiko** [comment]
If the auto discovery does not work it's likely that you are running it from a non git checkout. That issue however would be unrelated to this one here. I will close this issue as resolved. If you have that issue still please open another issue for it.

**Comment by ajtrichards** [comment]
I'm still getting the error : `error: For non git repositories explicit revisions are required`

I've updated to the latest version of the Sentry CLI:
```
[user@ip-X-X-X-X ~]$ sentry-cli --version
sentry-cli 1.35.6
```

My respositories are present also:
```
+---------------------------------------------------+----------+----------------------------------------------------------------------+
| Name                                              | Provider | URL                                                                  |
+---------------------------------------------------+----------+----------------------------------------------------------------------+
| EvaluAgent/REPONAME                             | GitHub   | https://github.com/EvaluAgent/REPONAME                             |
+---------------------------------------------------+----------+----------------------------------------------------------------------+
```

**Comment by ryanwilsonperkin** [comment]
We just started seeing this issue pop up again on CLI v1.36.2

**Comment by ryanwilsonperkin** [comment]
Some further notes: debugging the tool suggests that it's bailing out because it found a repository that was misconfigured which is preventing it from being able to continue iterating over the other (correctly configured) git repos.

@nickpresta is working on a patch for Sentry-Cli

**Comment by nickpresta** [comment]
I thought I could land a quick patch for this but I don't know enough about Rust to make a change with confidence.

I suspect there is a "hacky" fix in [this block](https://github.com/getsentry/sentry-cli/blob/38258cc/src/utils/vcs.rs#L212-L231) where the `found_non_git` is reset to `false` on every loop iteration to prevent using that value set by a previous iteration. However, I suspect something else is happening where the check against the `url` may be throwing unexpectedly due to the `null` value, because we see the following logging:

```
INFO    2018-11-01 11:16:24.270095 -04:00 Resolving HEAD (waveaccounting/cb-account-connection-form@HEAD)
DEBUG   2018-11-01 11:16:24.270280 -04:00   unknown repository unknown:17184 skipped
INFO    2018-11-01 11:16:24.270497 -04:00 Skipping update nagger update check
error: For non git repositories explicit revisions are required
DEBUG   2018-11-01 11:16:24.271604 -04:00 client close; no transport to shut down  (from sentry)
```

for the given payload (from the organizations API list):

```
    {
        "dateCreated": "2018-11-01T14:47:09.328Z",
        "id": "17184",
        "integrationId": null,
        "name": "waveaccounting/cb-account-connection-form",
        "provider": {
            "id": "unknown",
            "name": "Unknown Provider"
        },
        "status": "active",
        "url": null
    }
```

The project we're trying to create a release for, `publicsite` is listed after the `cb-account-connection-form` so it bails out early and never gets to the `publicsite` project.

**Comment by Elijen** [comment]
Any luck @ryanwilsonperkin?  It works for my on localhost, but fails in Bitbucket Pipeline.

**Comment by ryanwilsonperkin** [comment]
@Elijen we took a crack at this in a patch but couldn't get it working quite right, we "solved" it for ourselves by updating the repositories in our account. That unfortunately means we don't have an easy way to test our patch anymore and can't follow up.

**Comment by Elijen** [comment]
@ryanwilsonperkin Thanks for the info. Do you at least know what was causing it and what could be a workaround? How could I update the repositories to make it work for us to for example?

**Comment by ryanwilsonperkin** [comment]
@Elijen yeah in our case it was happening because one of the GitHub repositories we'd previously linked had been renamed and wasn't being fetched properly. This had the effect of breaking a loop over available repositories (returned by an API call) and making it seem as though the repository wasn't available. I'd suggest running `sentry-cli` in debug/verbose mode to see the additional logging output. It could be that you just need to delete your linked repositories and re-add them.

**Comment by Elijen** [comment]
@ryanwilsonperkin That's strange. We didn't rename repos for sure. I've checked the debug output of sentry-cli and it returns the repo in question correctly and with `"provider": { "id": "integrations:bitbucket", "name": "Bitbucket" },` `git status` confirms we are in a git checkout.

@mitsuhiko Would it make sense to reopen this issue?

**Comment by mitsuhiko** [comment]
@Elijen can you paste the contents of your `.git/config`? Also more importantly can you run in debug mode and paste the output.

**Comment by Elijen** [comment]
@mitsuhiko That's weird. We are using `sentry-expo@1.10.0` which is using `react-native-sentry@0.39.1` and `sentry-cli@1.36.4`. Not sure what's happening here.

**Comment by mitsuhiko** [comment]
I'm assuming you have another sentry-cli on your path that is being picked up or something similar. Not sure which version you have but that log format is very old. New sentry-cli looks very different.

**Comment by mitsuhiko** [comment]
Closing this as resolved then.

**Comment by gregholland** [comment]
I've just randomly started getting this error using `"@sentry/webpack-plugin": "^1.11.1"`
```
  Error: Command failed: /home/circleci/repo-name/node_modules/@sentry/cli/sentry-cli releases set-commits 1.26.1 --auto
  error: For non git repositories explicit revisions are required
```
